#!/usr/bin/env python3
#-*- coding: utf-8 -*-
'''PyWiSim main library.

Communications users are connected to a base station (class BaseStation) through a user data terminal equipment (class UserEquipment) which reaches the base station through a communications channel (cass Channel). The base station has a number of communications resources (class Resource) which can be assigned to users for transmission. The base stations administers its users and resources in groups called "slices" (class Slice); a slice is a collection of users and resources. A base stations manages several slices. Each slice manages its users and resources through a scheduler (class Scheduler), which assigns resources to users according to the users' profiles, resoources available, state of the communications channel, and other conditions. Traffic generated by the users is simulated by traffic generators (class TrafficGenerator) in the form of packets of variable size. These packets are added to a packet queue (class PacketQueue) linked to the user's data terminal equipment. Periodically, each slice in the base station transmits packets from the users' queues. The quantity of bits allowed to trnsmit is determined by the state of the channel, the number of symbols the resource can handle, the modulation scheme and other conditions, which determine the transport block size (class TransportBlock), the quantity of bits that can be transmitted, which in turn determmines the number of packets to extract from the queues.

Several classes in this library are abstract, e.g. Channel, ChannelEnvironment, TransportBlock, TrafficGenerator, Scheduler. These classes are implemented as concrete classes in the models directories. A simple simulator example which uses these concrete classes can be found in C{extensions/simplesim}. 

WARNING. Please note "slice" is a reserved word in Python, not so "Slice".
'''
